SELECT maxtotal.CUSTOMER_ACCOUNT_MASK, MAX(maxtotal.dif)
FROM (SELECT 
t1.CUSTOMER_ACCOUNT_MASK, t1.TRANSACTION_TIME_KEY Date1,
MAX(t2.TRANSACTION_TIME_KEY) Date2,
DATEDIFF(DATE_FORMAT(t1.TRANSACTION_TIME_KEY, '%Y-%m-%d'), DATE_FORMAT(MAX(t2.TRANSACTION_TIME_KEY), '%Y-%m-%d')) dif
FROM dim_total t1
LEFT JOIN dim_total t2 ON t1.CUSTOMER_ACCOUNT_MASK = t2.CUSTOMER_ACCOUNT_MASK
AND t1.TRANSACTION_TIME_KEY > t2.TRANSACTION_TIME_KEY
GROUP BY t1.CUSTOMER_ACCOUNT_MASK , t1.TRANSACTION_TIME_KEY
union
select t1.CUSTOMER_ACCOUNT_MASK, (20181231) Date1, max(t1.TRANSACTION_TIME_KEY) Date2,
DATEDIFF(DATE_FORMAT(20181231, '%Y-%m-%d'), DATE_FORMAT(MAX(IFNULL(t1.TRANSACTION_TIME_KEY, 20170101)), '%Y-%m-%d')) dif
from dim_total t1
GROUP BY CUSTOMER_ACCOUNT_MASK) as maxtotal
GROUP BY maxtotal.CUSTOMER_ACCOUNT_MASK;