SELECT ttt.CUSTOMER_ACCOUNT_MASK, HIERARCHY_PARENT_DSC, MAX(ttt.dif)
FROM (SELECT 
t1.CUSTOMER_ACCOUNT_MASK, ifnull(t1.HIERARCHY_PARENT_DSC,'UNKNOWN') as HIERARCHY_PARENT_DSC,t1.TRANSACTION_TIME_KEY Date1,
IFNULL(MAX(t2.TRANSACTION_TIME_KEY), 20170101) Date2,
DATEDIFF(DATE_FORMAT(t1.TRANSACTION_TIME_KEY, '%Y-%m-%d'), DATE_FORMAT(MAX(IFNULL(t2.TRANSACTION_TIME_KEY, 20170101)), '%Y-%m-%d')) dif
FROM dim_total t1
LEFT JOIN dim_total t2 ON t1.CUSTOMER_ACCOUNT_MASK = t2.CUSTOMER_ACCOUNT_MASK AND ifnull(t1.HIERARCHY_PARENT_DSC,'UNKNOWN') = ifnull(t2.HIERARCHY_PARENT_DSC,'UNKNOWN')
AND t1.TRANSACTION_TIME_KEY > t2.TRANSACTION_TIME_KEY
Where t1.CUSTOMER_ACCOUNT_MASK=50502158
GROUP BY t1.CUSTOMER_ACCOUNT_MASK , ifnull(t1.HIERARCHY_PARENT_DSC,'UNKNOWN'), t1.TRANSACTION_TIME_KEY
union
select t1.CUSTOMER_ACCOUNT_MASK,ifnull(t1.HIERARCHY_PARENT_DSC,'UNKNOWN') as HIERARCHY_PARENT_DSC, DATE_FORMAT(20181231, '%Y-%m-%d') Date1, max(t1.TRANSACTION_TIME_KEY) Date2,
DATEDIFF(DATE_FORMAT(20181231, '%Y-%m-%d'), DATE_FORMAT(MAX(IFNULL(t1.TRANSACTION_TIME_KEY, 20170101)), '%Y-%m-%d')) dif
from dim_total t1
where CUSTOMER_ACCOUNT_MASK = 50502158
GROUP BY CUSTOMER_ACCOUNT_MASK,ifnull(HIERARCHY_PARENT_DSC,'UNKNOWN')) as ttt
GROUP BY ttt.CUSTOMER_ACCOUNT_MASK,ttt.HIERARCHY_PARENT_DSC;