SELECT
T1.MERCH_KEY, T1.MERCH_CD,T1. T1.CITY, T1.MERCH_DSC, T1.COUNTRY
FROM
cartaocontinente.dim_merchant T1
/* Colunas a retirar: 
ADDRESS
POST_CODE
KEY_START_DATE
KEY_END_DATE
CRETAE_DATE
LAST_UPDT_DATE */